### ISSUE TITLE
Undefined symbols for architecture armv7:

### ISSUE THREAD

**Issue by mitty1987** [Sh1d0w/multi_image_picker#48]
Failed to build iOS app
Error output from Xcode build:
↳
    2018-12-29 13:31:33.319 xcodebuild[14018:896383]  DTDeviceKit: deviceType from 104464efaa9c749423ba37dc8045a23c092c5e56 was NULL
    ** BUILD FAILED **

Xcode's output:
↳
    Undefined symbols for architecture armv7:
      "17UIViewContentModeVN", referenced from:
          __swift_FORCE_LOAD_$_swiftObjectiveC_$_BSImageView in ImageViewLayout.o
      "geB6LayoutV16imageHeightRatio33_236E416D1770FBCDB78F93EDC4C11DCELL_9container12CoreGraphics7CGFloatVSo6CGSizeV_AKtFZ", referenced from:
          full type metadata for BSImageView.ImageViewLayout in ImageViewLayout.o
      "___ 11BSImageView05ImageB6LayoutV", referenced from:
          static BSImageView.ImageViewLayout.(positionForImage in _236E416D1770FBCDB78F93EDC4C11DCE)(_: __C.CGSize, previousPosition: __C.CGPoint, container: __C.CGSize, contentMode: __C.UIViewContentMode) -> __C.CGPoint in ImageViewLayout.o
      "hics7CGFloatVSo6CGSizeV_AKtFZ", referenced from:
          static BSImageView.ImageViewLayout.(sizeForImage in _236E416D1770FBCDB78F93EDC4C11DCE)(_: __C.CGSize, previousSize: __C.CGSize, container: __C.CGSize, contentMode: __C.UIViewContentMode) -> __C.CGSize in ImageViewLayout.o
         (maybe you meant: utV16imageHeightRatio33_236E416D1770FBCDB78F93EDC4C11DCELL_9container12CoreGraphics7CGFloatVSo6CGSizeV_AKtFZ, Ratio33_236E416D1770FBCDB78F93EDC4C11DCELL_9container12CoreGraphics7CGFloatVSo6CGSizeV_AKtFZ , 0FBCDB78F93EDC4C11DCELL_9container12CoreGraphics7CGFloatVSo6CGSizeV_AKtFZ , w05ImageB6LayoutV15imageWidthRatio33_236E416D1770FBCDB78F93EDC4C11DCELL_9container12CoreGraphics7CGFloatVSo6CGSizeV_AKtFZ , mageWidthRatio33_236E416D1770FBCDB78F93EDC4C11DCELL_9container12CoreGraphics7CGFloatVSo6CGSizeV_AKtFZ , 11DCELL_9container12CoreGraphics7CGFloatVSo6CGSizeV_AKtFZ )
      "eV_AKtFZ", referenced from:
          static BSImageView.ImageViewLayout.(sizeForImage in _236E416D1770FBCDB78F93EDC4C11DCE)(_: __C.CGSize, previousSize: __C.CGSize, container: __C.CGSize, contentMode: __C.UIViewContentMode) -> __C.CGSize in ImageViewLayout.o
         (maybe you meant: SizeV_AKtFZ, utV16imageHeightRatio33_236E416D1770FBCDB78F93EDC4C11DCELL_9container12CoreGraphics7CGFloatVSo6CGSizeV_AKtFZ , Ratio33_236E416D1770FBCDB78F93EDC4C11DCELL_9container12CoreGraphics7CGFloatVSo6CGSizeV_AKtFZ , 0FBCDB78F93EDC4C11DCELL_9container12CoreGraphics7CGFloatVSo6CGSizeV_AKtFZ , w05ImageB6LayoutV15imageWidthRatio33_236E416D1770FBCDB78F93EDC4C11DCELL_9container12CoreGraphics7CGFloatVSo6CGSizeV_AKtFZ , mageWidthRatio33_236E416D1770FBCDB78F93EDC4C11DCELL_9container12CoreGraphics7CGFloatVSo6CGSizeV_AKtFZ , 11DCELL_9container12CoreGraphics7CGFloatVSo6CGSizeV_AKtFZ )
      "416D1770FBCDB78F93EDC4C11DCELL_9container12CoreGraphics7CGFloatVSo6CGSizeV_AKtFZ", referenced from:
          static BSImageView.ImageViewLayout.(positionForImage in _236E416D1770FBCDB78F93EDC4C11DCE)(_: __C.CGSize, previousPosition: __C.CGPoint, container: __C.CGSize, contentMode: __C.UIViewContentMode) -> __C.CGPoint in ImageViewLayout.o
         (maybe you meant: utV16imageHeightRatio33_236E416D1770FBCDB78F93EDC4C11DCELL_9container12CoreGraphics7CGFloatVSo6CGSizeV_AKtFZ, Ratio33_236E416D1770FBCDB78F93EDC4C11DCELL_9container12CoreGraphics7CGFloatVSo6CGSizeV_AKtFZ , w05ImageB6LayoutV15imageWidthRatio33_236E416D1770FBCDB78F93EDC4C11DCELL_9container12CoreGraphics7CGFloatVSo6CGSizeV_AKtFZ , mageWidthRatio33_236E416D1770FBCDB78F93EDC4C11DCELL_9container12CoreGraphics7CGFloatVSo6CGSizeV_AKtFZ )
      "12CoreGraphics7CGFloatVSo6CGSizeV_AKtFZ", referenced from:
          static BSImageView.ImageViewLayout.(sizeForImage in _236E416D1770FBCDB78F93EDC4C11DCE)(_: __C.CGSize, previousSize: __C.CGSize, container: __C.CGSize, contentMode: __C.UIViewContentMode) -> __C.CGSize in ImageViewLayout.o
         (maybe you meant: utV16imageHeightRatio33_236E416D1770FBCDB78F93EDC4C11DCELL_9container12CoreGraphics7CGFloatVSo6CGSizeV_AKtFZ, Ratio33_236E416D1770FBCDB78F93EDC4C11DCELL_9container12CoreGraphics7CGFloatVSo6CGSizeV_AKtFZ , 0FBCDB78F93EDC4C11DCELL_9container12CoreGraphics7CGFloatVSo6CGSizeV_AKtFZ , w05ImageB6LayoutV15imageWidthRatio33_236E416D1770FBCDB78F93EDC4C11DCELL_9container12CoreGraphics7CGFloatVSo6CGSizeV_AKtFZ , mageWidthRatio33_236E416D1770FBCDB78F93EDC4C11DCELL_9container12CoreGraphics7CGFloatVSo6CGSizeV_AKtFZ , 11DCELL_9container12CoreGraphics7CGFloatVSo6CGSizeV_AKtFZ )
      "static BSImageView.ImageViewLayout.frameForImageWithSize(_: __C.CGSize, previousFrame: __C.CGRect, inContainerWithSize: __C.CGSize, usingContentMode: __C.UIViewContentMode) -> __C.CGRect", referenced from:
          BSImageView.BSImageView.layoutSubviews() -> () in BSImageView.o
    ld: symbol(s) not found for architecture armv7
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Sh1d0w** [comment]
Hi, did you follow the steps to enable Swift support for your project?

https://sh1d0w.github.io/multi_image_picker/#/iostroubleshooting

Also take a look at this issue https://github.com/Sh1d0w/multi_image_picker/issues/38

**Comment by mitty1987** [comment]
@Sh1d0w 
yes, the project can build success in command line and also can run with xcode.

**Comment by Sh1d0w** [comment]
@mitty1987 What is your build target, is it a generic device? Also can you put the output from `flutter doctor`?

**Comment by mitty1987** [comment]
@Sh1d0w 
private-2:ios chenjian$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.2 18C54, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] Connected device (1 available)

• No issues found!

**Comment by Sh1d0w** [comment]
@mitty1987 I've just released version `2.3.28`, can you try to see if this solves your issue?

Please do:

1. Change version in pub spec to `2.3.28`
2. `flutter packages get`
3. flutter clean
4. `flutter build ios`
5. `flutter run`

**Comment by mitty1987** [comment]
@Sh1d0w 
Follow the setps，build faild...
private-2:ks_pet chenjian$ flutter build ios
Building com.huobao123.www for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project:
JC9K9M3TW2
Running pod install...                                       4.1s
Starting Xcode build...
Xcode build done.                                            6.8s
Failed to build iOS app
Error output from Xcode build:
↳
    2018-12-29 14:45:09.138 xcodebuild[26840:954156]  DTDeviceKit: deviceType from
    104464efaa9c749423ba37dc8045a23c092c5e56 was NULL
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET FMDB OF PROJECT Pods WITH CONFIGURATION Release ===
    /Users/chenjian/Library/Developer/Xcode/DerivedData/Runner-agcqebtvyioymeeijnfbdmvjlnja/Build/I
    ntermediates.noindex/Pods.build/Release-iphoneos/BSImageView.build/unextended-module.modulemap:
    2:19: error: umbrella header 'BSImageView-umbrella.h' not found
      umbrella header "BSImageView-umbrella.h"
                      ^
    <unknown>:0: error: could not build Objective-C module 'BSImageView'

Encountered error while building for device.

**Comment by Sh1d0w** [comment]
Can you try to go to your `ios` folder remove Podfile.lock and Pods directory and do

`pod install --repo-update`

Then try flutter clean and flutter build `ios`

Can you also try and see if you can run the example app in my repo and let me know?

**Comment by mitty1987** [comment]
@Sh1d0w 
I can build in commind line now
<img width="703" alt="default" src="https://user-images.githubusercontent.com/11976492/50534673-ef498800-0b7a-11e9-97b1-1725f91943a7.png">
but,android studio build still faild:
<img width="1069" alt="default" src="https://user-images.githubusercontent.com/11976492/50534677-0ab49300-0b7b-11e9-9eeb-6b569ff64a55.png">

the example build faild too:
<img width="1568" alt="default" src="https://user-images.githubusercontent.com/11976492/50534693-56ffd300-0b7b-11e9-924d-259c47addf16.png">

**Comment by mitty1987** [comment]
@Sh1d0w Sorry, i forgot to set signing when first run.Your example is run success.so,what happen with my app,I just do nothing except add dependencies in pubspec...

**Comment by Sh1d0w** [comment]
@mitty1987 From your second screenshot I see that the first error you get is:

`dtdevicekit devicetype from was null`

Which may lead to the second error in my package. For some reason the deviceType of your connected device is NULL.

If you can run my example app on your phone fine, then it may be something with the configuration on your project and I would suggest you to compare both `Podfile` in your `ios` project and my example app to see what's different.

Otherwise if you are not able to run the example app on your phone either I would suggest you to do a Google search how to fix the first error with your device, as I am not able to reproduce the error you are getting.

**Comment by mitty1987** [comment]
@Sh1d0w 
I created an clean project and copy all file to the project then it's work.I don't know why, whatever...
Please close this issues and thank you for your help.
